name: upload docker image

on:
    push:

jobs:
  upload_docker_server_debug_image:
    name: "upload_docker_server_debug_image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Make the build
        run: |
            make docker-server-debug
      - name: Push the image
        run: |
            docker tag bombsquad_server_debug:latest ghcr.io/${{ github.repository }}/bombsquad_server_debug:latest